version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-api
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: npm run dev
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Users
    ports:
      - 27017:27017